version: "3.9"
services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
     - wordpress:/var/www/html
    networks:
      - mynet
    env_file:
      - .env
    depends_on:
      - wordpress
    container_name: nginx
    restart: always
  wordpress:
    build: ./requirements/wordpress
    volumes:
     - wordpress:/var/www/html
    restart: always
    networks:
      - mynet
    env_file:
      - .env
    depends_on:
      - mariadb
    container_name: wordpress
  mariadb:
    build:
      context: ./requirements/mariadb
      args:
        - DB_USER
        - DB_NAME
        - DB_PASSWORD
        - DB_ROOT_PASSWORD
    networks:
      - mynet
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    env_file:
      - .env
    container_name: mariadb
  redis:
    build: ./requirements/bonus/redis
    networks:
      - mynet
  adminer:
    build: ./requirements/bonus/adminer
    ports:
      - 8000:8000
    networks:
      - mynet
    restart: always
    container_name: adminer
  portainer:
    build: ./requirements/bonus/portainer
    networks:
      - mynet
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
  ftp:
    ports:
      - 21:21
    build:
      context: ./requirements/bonus/ftp
      args:
        - FTP_PASS
    volumes:
      - wordpress:/home/ftpuser/wordpress
    networks:
      - mynet
    restart: always
    container_name: ftp
volumes:
    wordpress:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: ${HOME}/data/wordpress
    mariadb:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: ${HOME}/data/mariadb
networks:
  mynet:
    driver: bridge