version: "3.9"
services:
  nginx:
    build: ./requirements/nginx
    image: nginx
    ports:
      - "443:443"
    volumes:
     - wordpress:/var/www/html
    networks:
      - mynet
    env_file:
      - .env
    depends_on:
      - wordpress
    init: true
    container_name: nginx
    restart: always
  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    volumes:
     - wordpress:/var/www/html
    restart: always
    networks:
      - mynet
    env_file:
      - .env
    init: true
    depends_on:
      - mariadb
    container_name: wordpress
  mariadb:
    image: mariadb
    build:
      context: ./requirements/mariadb
      args:
        - DB_USER
        - DB_NAME
        - DB_PASSWORD
        - DB_ROOT_PASSWORD
    init: true
    networks:
      - mynet
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    env_file:
      - .env
    container_name: mariadb
  redis:
    build: ./requirements/bonus/redis
    image: redis
    init: true
    networks:
      - mynet
    container_name: redis
  adminer:
    build: ./requirements/bonus/adminer
    image: adminer
    ports:
      - 8000:8000
    networks:
      - mynet
    restart: always
    init: true
    container_name: adminer
  portainer:
    build: ./requirements/bonus/portainer
    image: portainer
    networks:
      - mynet
    ports:
      - 9000:9000
    container_name: portainer
    init: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    restart: always
  vsftpd:
    ports:
      - 21:21
    init: true
    image: vsftpd
    build:
      context: ./requirements/bonus/ftp
      args:
        - FTP_PASS
    volumes:
      - wordpress:/home/ftpuser/wordpress
    networks:
      - mynet
    restart: always
    container_name: vsftpd
  portfolio:
    build: ./requirements/bonus/portfolio
    image: portfolio
    ports:
      - 1337:80
    networks:
      - mynet
    init: true
    container_name: portfolio
volumes:
    wordpress:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: ${HOME}/data/wordpress
    mariadb:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: ${HOME}/data/mariadb
    portainer:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: ${HOME}/data/portainer
networks:
  mynet:
    driver: bridge