version: "3.9"
services:
  nginx:
    build: srcs/requirements/nginx
    ports:
      - "443:443"
    volumes:
     - wordpress:/var/www/html
    networks:
      - mynet
    depends_on:
      - wordpress
  wordpress:
    build: srcs/requirements/wordpress
    volumes:
     - wordpress:/var/www/html
    restart: always
    networks:
      - mynet
    env_file:
      - .env
    depends_on:
      - mariadb
  mariadb:
    build:
      context: srcs/requirements/mariadb
      args:
        - DB_USER
        - DB_NAME
        - DB_PASSWORD
    networks:
      - mynet
    restart: always
    env_file:
      - .env
  redis:
    build: srcs/requirements/bonus/redis
    networks:
      - mynet
  adminer:
    build: srcs/requirements/bonus/adminer
    ports:
      - 8000:8000
    networks:
      - mynet
  portainer:
    build: srcs/requirements/bonus/portainer
    networks:
      - mynet
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  ftp:
    ports:
      - 21:21
    build: srcs/requirements/bonus/ftp
    volumes:
      - wordpress:/home/ftpuser/wordpress
    networks:
      - mynet
volumes:
    wordpress:
      driver: local
networks:
  mynet:
    driver: bridge